#######################   AnvilCommands Config   #######################
##
##
##############   Placeholders and Special AnvilCommands tags   #########
## Use %userinput% to input whatever the player has typed into the GUI text box When Executing a Command
## Use %player% to input the Player's Name When Executing a Command
## Prefix a Command with ! to run the command as the player with OP
## Prefix a Command with ~ To run the command as the console
#############################################################################
## config:
##   commands:
## Below Here is Where you Define your commands
## Blah blah blah explain more here 
## You can copy and paste the examples and edit them as you learn how to use the plugin
##     newtown:
##       ^^Creates a new command called /newtown, this is where you name the command for your anvilGUI. This is the only
##         Config header you should be editing
##       permission: anvilcommands.newtown
##            permission to open this Anvil GUI
##       type: ANVIL or SIGN
##       prompt: "Town Name :"
##            ##The text for the item in Slot1 and the default text in the textbox in anvils, and a
##            ##prompt that appears on the screen before the sign GUI pops up. Doesn't accept colors
##            ##In the Anvil GUI
##       result:
##         command:
##         - 't new %userinput%'
##         - 't deposit 1000'  
#################################################################################
config:
  commands:
    newtown:
      ##Creates a new command called /newtown
      permission: anvilcommands.newtown
      type: ANVIL
      ##permission to open this Anvil GUI
      prompt: "Town Name :"
      result:
        command:
        - 't new %userinput%'
    renameme:
      ## Creates a new command called /renameme
      permission: anvilcommands.renameme
      type: SIGN
      ##permission to open this SIGN GUI
      prompt: "&4Please Enter your new Nickname in the &rSign GUI &4that pops up"
      result:
        command:
        - "!nick %userinput%"
        ## Executes as the player as OP